export const products = [
  {
    label: "Trail Ipsum shirt",
    amount: 120,
    image: "bg-man-1",
    image2: "group-hover:bg-man-1-back",
    star: 5,
  },
  {
    label: "Trail Ipsum shirt",
    amount: 120,
    image: "bg-man-2",
    image2: "group-hover:bg-man-2-back",
    star: 5,
  },
  {
    label: "Trail Ipsum shirt",
    amount: 120,
    image: "bg-man-1",
    image2: "group-hover:bg-man-1-back",
    star: 5,
  },
  {
    label: "Trail Ipsum shirt",
    amount: 120,
    image: "bg-man-2",
    image2: "group-hover:bg-man-2-back",
    star: 5,
  },
  {
    label: "Trail Ipsum shirt",
    amount: 120,
    image: "bg-man-1",
    image2: "group-hover:bg-man-1-back",
    star: 5,
  },
  {
    label: "Trail Ipsum shirt",
    amount: 120,
    image: "bg-man-2",
    image2: "group-hover:bg-man-2-back",
    star: 5,
  },
  {
    label: "Trail Ipsum shirt",
    amount: 120,
    image: "bg-man-1",
    image2: "group-hover:bg-man-1-back",
    star: 5,
  },
  {
    label: "Trail Ipsum shirt",
    amount: 120,
    image: "bg-man-2",
    image2: "group-hover:bg-man-2-back",
    star: 5,
  },
];
